name: Attendance Automation

on:
  schedule:
    # Run at 4:45 AM UTC, which is 10:15 AM IST, Monday to Friday
    - cron: '45 4 * * 1-5'
    # Run at 1:00 PM UTC, which is 6:30 PM IST, Monday to Friday
    - cron: '0 13 * * 1-5'
  workflow_dispatch:

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          pip install selenium
          pip install requests
          pip install chromedriver-autoinstaller
          pip install pyvirtualdisplay
          pip install pytz

      - name: Run Selenium script
        run: |
          python attendance.py
          # python attendance_v2.py
        env:
          DISPLAY: :99
          SYB_EMAIL_PASSWORD: ${{ secrets.SYB_EMAIL_PASSWORD }} 
          SYB_ATTENDANCE_PORTAL_PASSWORD: ${{ secrets.SYB_ATTENDANCE_PORTAL_PASSWORD }} 
