name: Attendance Automation

on:
  schedule:
    - cron: '0 10,18 * * 1-5'
  workflow_dispatch:

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxss1 libappindicator3-1 libindicator7
          sudo apt-get install -y xvfb
          pip install selenium
          pip install requests
          pip install chromedriver-autoinstaller

      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          nohup Xvfb :99 &

      - name: Run Selenium script
        run: |
          python attendance.py
        env:
          DISPLAY: :99
